services:
  conferences-service:
    image: conferences-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://conferences-db:5432/conferences
      SPRING_PROFILES_ACTIVE: default, admin
      ADMIN_PASSWORD: admin
      DB_URL: conferences-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    networks:
      - conferences-network
    depends_on:
      - conferences-db
  conferences-db:
    image: harbor.avalaunch.aval/docker-hub-proxy/postgres:15
    environment:
      POSTGRES_DB: "conferences"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    networks:
      - conferences-network
  boot-admin:
    image: boot-admin:latest
    build:
      context: ./boot-admin
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - conferences-network
networks:
  conferences-network: