server:
  port: 9999
spring:
  flyway:
    table: conferece_service_flyway_schema_history
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:h2:file:./db/conference
    driverClassName: org.h2.Driver
    username: conf
    password: conf
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true