openapi: 3.0.0
info:
  description: Conferences Service
  version: FINAL
  title: Conferences API
tags:
  - name: conferences
  - name: talks
paths:
  /conferences:
    post:
      description: Add conference.
      tags:
        - conferences
      operationId: addConference
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConferenceDto'
        required: true
      responses:
        '201':
          description: Added conference
          content:
            application/json:
              schema:
                type: integer
                format: int32
        '400':
          description: Bad Request
    get:
      description: Retrieve all available conferences.
      tags:
        - conferences
      operationId: allConferences
      responses:
        '200':
          description: List of conferences.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConferenceDto'
  /conferences/{conferenceId}:
    put:
      description: Retrieve conference by conferenceId.
      tags:
        - conferences
      operationId: updateConference
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConferenceDto'
        required: true
      responses:
        204:
          description: Conferences.
        400:
          description: Bad Request
        404:
          description: NOT FOUND
  /conferences/{conferenceId}/talks:
    post:
      description: Add new talk.
      tags:
        - talks
      operationId: addTalk
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            nullable: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TalkDto'
        required: true
      responses:
        201:
          description: Added new talk.
    get:
      description: List of talks by conferenceId.
      tags:
        - talks
      operationId: retrieveTalksByConferenceId
      parameters:
        - name: conferenceId
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
            minimum: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TalkDto'
        404:
          description: NOT FOUND
components:
  schemas:
    ConferenceDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          $ref: '#/components/schemas/nonEmptyString'
        topic:
          $ref: '#/components/schemas/nonEmptyString'
        dateStart:
          type: string
          nullable: false
          minLength: 1
          pattern: '(\d{4})-(\d{2})-(\d{2})'
        dateEnd:
          type: string
          nullable: false
          minLength: 1
          pattern: '(\d{4})-(\d{2})-(\d{2})'
        participants:
          type: integer
          format: int32
          nullable: false
          minimum: 101
      required:
        - name
        - topic
        - dateStart
        - dateEnd
        - participants
    TalkDto:
      type: object
      properties:
        title:
          $ref: '#/components/schemas/nonEmptyString'
        description:
          $ref: '#/components/schemas/nonEmptyString'
        speaker:
          $ref: '#/components/schemas/nonEmptyString'
        talkType:
          type: string
          nullable: false
          enum:
            - REPORT
            - MASTER_CLASS
            - WORKSHOP
      required:
        - title
        - description
        - speaker
        - talkType
    nonEmptyString:
      type: string
      nullable: false
      minLength: 1
    nonEmptyInteger:
      type: integer
      format: int32
      nullable: false
      minimum: 1